### ISSUE TITLE
Add support to customize Compass direction to support other languages

### ISSUE THREAD

**Issue by afucher** [nerdstep/react-coordinate-input#45]
Hi,

It would be good to have some way to change the default `NS/EW`chars.
This will allow to be used with other languages than English.

I was thinking in something like what you have today for other chars: 
```
degreeChar: '°',
  minuteChar: '′',
  secondChar: '″',
  spacerChar: ' ',
```

What do you think? I can implement that.

**Comment by nerdstep** [comment]
@afucher I think that's a great idea. I'd be happy to accept the changes if you'd like to submit a PR.
