### ISSUE TITLE
Break into lat and long inputs

### ISSUE THREAD

**Issue by afucher** [nerdstep/react-coordinate-input#46]
What about export also 2 different inputs?

**Comment by nerdstep** [comment]
It's possible however this would change up the internals a bit. One idea I'm currently considering for the next version is to simply provide a React Hook that returns the mask and then let users connect it to their own input. Perhaps with this approach it would easier to provide different masks for this use case.

**Comment by afucher** [comment]
I thought about that, it would be great!

**Comment by afucher** [comment]
Are you already working on that?

**Comment by nerdstep** [comment]
No I haven't begun any work on it yet, my schedule has been quite busy so I haven't had an opportunity.
