### ISSUE TITLE
Testing with fireEvent 

### ISSUE THREAD

**Issue by afucher** [nerdstep/react-coordinate-input#47]
Hi, I'm trying to do some tests in my application that is using coordinate input.
But when I try to use react testing library to Change the input value with fireEvent.click the input seems to not call onChange

**Comment by nerdstep** [comment]
Yeah, I noticed this as well, you basically have to re-render the component with a new value for it to trigger the change -- or at least that's what I did in my tests. I'm blaming this on `imaskjs` which seems to take control of all input events.
